export const SIGNIN_USER = "@SIGNIN_USER",
	SIGNOUT_USER = "@SIGNOUT_USER",
	SET_PASSWORD = "@SET_PASSWORD",
	GET_ADD_CARS = "@GET_ADD_CARS",
	GET_CR_MMR = "@GET_CR_MMR",
	ADD_CAR = "@ADD_CAR",
	SUBBMIT_FORM = "@SUBBMIT_FORM",
	SIGNUP_USER= "@SIGNUP_USER";
