export const SIGNIN_USER = "@SIGNIN_USER",
	SIGNOUT_USER = "@SIGNOUT_USER",
	CREATE_USER="@CREATE_USER",
	SET_PASSWORD = "@SET_PASSWORD",
	SUBBMIT_POST = "@SUBBMIT_POST",
	SIGNUP_USER= "@SIGNUP_USER",
	GET_POST="@GET_POST";
